services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=happyadoption'
      - 'POSTGRES_PASSWORD=somesecret'
      - 'POSTGRES_USER=happyadoption'
    ports:
         - "5432:5432"
    volumes:
          - hpn:/var/lib/postgresql/data
volumes:
  hpn: